version: '3.8'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'tele-support-mysql'
    restart: 'always'
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data:
